#!/bin/bash
#
# Reads pids from the 'pids.ids' file and kills all of them.

# readarray -d '' PIDS < <(cat pids.ids)
mapfile -d $'\0' PIDS < <(cat pids.ids)

for pid in ${PIDS[@]}; do
    echo "Stopping pid $pid"
    pkill -9 -P $pid
    kill -10 $pid
done